### ISSUE TITLE
Use the new `compilation.chunkGroups` for better performance

### ISSUE THREAD

**Issue by satazor** [diegohaz/webpack-sort-chunks#3]
The new version of https://github.com/jantimon/html-webpack-plugin/blob/master/lib/chunksorter.js#L30 now uses `compilation.chunkGroups` which in turns makes the algorithm faster.

Moreover, this package started to throw a cyclic error when I applied the `splitChunks` optimization here: https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file. Though, when using https://github.com/jantimon/html-webpack-plugin/blob/master/lib/chunksorter.js, there's no error at all.

Do you accept  PR by adding an optional `compilation` argument and using it if supplied?

Thanks.

**Comment by diegohaz** [comment]
Sure. Feel free to send the PR. :)
